### ISSUE TITLE
ERPNext (online) Shopify Sync error

### ISSUE THREAD

**Issue by James246810** [frappe/erpnext_shopify#118]
Hi All,

I would really appreciate your help as one of the big reasons I decided to use ERPNext was becuase of the connect with Shopify app.

**ERPNext shopify app error when it self terminated:**

**Method =** sync_shopify_resources

**Message =** 
Traceback (innermost last):
  File "/home/frappe/press/benches/1606241046/apps/erpnext_shopify/erpnext_shopify/api.py", line 37, in sync_shopify_resources
    update_item_stock_qty()
  File "/home/frappe/press/benches/1606241046/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 542, in update_item_stock_qty
    if e.args[0] and e.args[0].startswith("402"):
 IndexError: tuple index out of range

Many thanks for your help.

Kind regards James

**Comment by saurabh6790** [comment]
@James246810  Thanks for reporting an issue. We have fixed this issue but it's not yet released.

**Comment by James246810** [comment]
Great thanks Saurabh much appreciated.   I have also noticed that images
are no loner been brought over as they were before.  Can this be fixed?
Many thanks for your help as always as I love erpnext and really need the
shopify app to work smoothly. Your help is very much appreciated.

Kind regards James

**Comment by saurabh6790** [comment]
@James246810 Sorry, but unfortunately I could not able to reproduce a image sync issue. Is there any error log related to image sync? If yes please share. Or can you share a scenario ?
Thanks.

**Comment by James246810** [comment]
Hi Saurabh,

Thank you for your email.

You are correct there is no error showing on the log files.  None in the
shopify log or the store log.

I can show you a visual screen shot however.  Here is erpnext:

[image: Inline images 1]

Here is my shopify store:

[image: Inline images 2]

As you can see there is an image in shopfiy but nothing showing in erpnext
even though all the boxes in erpnext are ticked to sync it to the my
shopify store.

I hope this helps and please let me know if you need anything else.

Many thanks for your help and I look forward to hearing from you.

Kind Regards 

James

**Comment by yashodhank** [comment]
@James246810 You should attach image on github.com directly instead of mailing it as reply, as it does not work most of the time.

**Comment by saurabh6790** [comment]
@James246810 Please reshare images. 
Thank you.

**Comment by James246810** [comment]
Hi saurabh6790,

Thank you for your help.  The screen shots contain sensitive business data.  Is there any way I can send you them directly or privately without sharing them with the world on github?

Many thanks for your support and I must say your doing a great job.

I look forward to hearing from you.

Best wishes
James

**Comment by saurabh6790** [comment]
@James246810, sure you can send it to saurabh@erpnext.com

**Comment by saurabh6790** [comment]
fixed
