### ISSUE TITLE
Installed module in v5 but unable to see it

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext_shopify#5]
Hi, I've installed the module in v5 but unable to see the module on the dashboard. How do I enable it?

**Comment by jk2081** [comment]
I would be very interested in this connector.

**Comment by asanchezg** [comment]
I already installed but I can't see module on dashboard. How to access to the module configuration ??

SOLUTION: I answer myself :)  Once you install the module you can set it up at SETUP / INTEGRATIONS / SHOPIFY SETTINGS
