### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext_shopify#95]
Can we keep the sync of products one way like products should be only synced from erpnext to shopify and not vise-versa,let me know if this is possible?

**Comment by anandpdoshi** [comment]
@Nehamirpuri this could create a problem when syncing orders. What's the use case?

**Comment by Nehamirpuri** [comment]
Anand,

We require this feature only for items and orders can sync.
The reason erp is a database for all items that we use in quote,purchase order and shopify too but not necessary all items need to have same description but here if a product we require certain description only in shopify we are unable to do so as all the description gets synced back to erp and same description is used in all other transaction where those details are un-necessary.
Either a different option can be that we have a separate description field for shopify like we had for erp website so there is no issue only.

**Comment by anandpdoshi** [comment]
ok so a **Shopify Description** is the requirement. That is doable. @saurabh6790 can you look into this.

The problem with selective syncing of items is that orders cannot be created in ERPNext for items that don't exist.

**Comment by Nehamirpuri** [comment]
Anand,

No the items shall exist only the description changes we do in shopify will not be synced back to erpnext item database.
But even if you provide us a separate description field for shopify that will solve the issue.

**Comment by saurabh6790** [comment]
@Nehamirpuri, we can add one field **Shopify Description**.

**Comment by Nehamirpuri** [comment]
Hi saurabh,

Thanks that will be a great help :),let me know when are you planning to add so we can move data from main description field to shopify description.

**Comment by Nehamirpuri** [comment]
Hi saurabh,

Any update on adding another description field for shopify ?

**Comment by Nehamirpuri** [comment]
Hi @saurabh6790,

Any update on adding another description field for shopify ?

**Comment by saurabh6790** [comment]
@Nehamirpuri yes I have added this functionality and its under test.
